# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from search_crawl_client.models.base_crawl_request import BaseCrawlRequest
from search_crawl_client.models.cache_config import CacheConfig
from search_crawl_client.models.crawl_many_request import CrawlManyRequest
from search_crawl_client.models.crawl_request import CrawlRequest
from search_crawl_client.models.general_search_crawl_request import GeneralSearchCrawlRequest
from search_crawl_client.models.general_search_crawl_result import GeneralSearchCrawlResult
from search_crawl_client.models.general_search_request import GeneralSearchRequest
from search_crawl_client.models.general_search_result import GeneralSearchResult
from search_crawl_client.models.http_validation_error import HTTPValidationError
from search_crawl_client.models.image_search_crawl_request import ImageSearchCrawlRequest
from search_crawl_client.models.image_search_crawl_result import ImageSearchCrawlResult
from search_crawl_client.models.image_search_request import ImageSearchRequest
from search_crawl_client.models.image_search_result import ImageSearchResult
from search_crawl_client.models.scrape_result import ScrapeResult
from search_crawl_client.models.ttl import Ttl
from search_crawl_client.models.validation_error import ValidationError
from search_crawl_client.models.validation_error_loc_inner import ValidationErrorLocInner
