# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelName(str, Enum):
    """
    ModelName
    """

    """
    allowed enum values
    """
    GENERALENGINEPRESET = 'GeneralEnginePreset'
    IMAGEENGINEPRESET = 'ImageEnginePreset'
    LEFT_SQUARE_BRACKET_A_COMMA__B_RIGHT_SQUARE_BRACKET = '[a, b]'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelName from a JSON string"""
        return cls(json.loads(json_str))


