services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/healthz",
        ]
      interval: 1s
      timeout: 1s
      retries: 15
    volumes:
      - ./searxng:/etc/searxng
    networks:
      - searxng-net

  api:
    build:
      context: .
    container_name: searxng-api
    ports:
      - "8000:8000"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--tries=1",
          "--spider",
          "--quiet",
          "http://127.0.0.1:8000/healthz",
        ]
      interval: 1s
      timeout: 1s
      retries: 15
    networks:
      - searxng-net

networks:
  searxng-net:
    driver: bridge
