services:
  search-crawl-searxng:
    image: searxng/searxng
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "-O",
          "/dev/null",
          "http://localhost:8080/healthz",
        ]
      interval: 1s
      timeout: 1s
      retries: 15
    volumes:
      - ./searxng:/etc/searxng
    pull_policy: always
    networks:
      - search-crawl-net

  search-crawl-redka:
    image: nalgeon/redka:latest
    ports:
      - "6379:6379"
    volumes:
      - ./.cache:/data
    command: /data/redka.db
    networks:
      - search-crawl-net

  search-crawl-main:
    build:
      context: .
    command: uv run --no-sync fastapi run src/search_crawl/main.py --host 0.0.0.0
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      - search-crawl-searxng
      - search-crawl-redka
    environment:
      - REDIS_URL=redis://search-crawl-redka:6379
      - SEARXNG_URL=http://search-crawl-searxng:8080
    healthcheck:
      test: [
          "CMD",
          "wget",
          "--tries=1",
          "--quiet",
          "-O",
          "/dev/null",
          "http://127.0.0.1:8000/healthz", # avoid localhost resolving to IPv6 ::1
        ]
      interval: 1s
      timeout: 1s
      retries: 15
    networks:
      - search-crawl-net

networks:
  search-crawl-net:
    driver: bridge
