services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/healthz",
        ]
      interval: 1s
      timeout: 1s
      retries: 15
    volumes:
      - ./searxng:/etc/searxng
