[project]
name = "search-crawl"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.14",
]

[tool.uv]
package = true

[tool.uv.sources]
openapi-client = { path = "openapi_client" }

[dependency-groups]
dev = [
    "openapi-client",
    "openapi-generator-cli[jdk4py]>=7.14.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
]
