[project]
name = "search-crawl"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "camoufox>=0.4.11",
    "cashews[diskcache]>=7.4.0",
    "cssselect>=1.3.0",
    "fastapi[standard]>=0.115.14",
    "lxml>=5.4.0",
    "markitdown>=0.1.2",
    "readability-lxml>=0.8.4.1",
]

[tool.uv]
package = true

[tool.uv.sources]
openapi-client = { path = "openapi_client" }

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "openapi-client",
    "openapi-generator-cli[jdk4py]>=7.14.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "types-lxml>=2025.3.30",
]
