# coding: utf-8

# flake8: noqa

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CacheConfig",
    "CrawlConfig",
    "CrawlExtractRequest",
    "CrawlRequest",
    "CrawlRequestWithUrl",
    "CrawlRequestWithUrls",
    "CrawlScope",
    "EnginePresetKey",
    "Engines",
    "ExtractRequest",
    "HTTPValidationError",
    "OutputFormat",
    "ScrapeResult",
    "SearchCrawlExtractRequest",
    "SearchCrawlRequest",
    "SearchCrawlResult",
    "SearchRequest",
    "SearchResult",
    "ValidationError",
    "ValidationErrorLocInner",
]

# import apis into sdk package
from search_crawl_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from search_crawl_client.api_response import ApiResponse as ApiResponse
from search_crawl_client.api_client import ApiClient as ApiClient
from search_crawl_client.configuration import Configuration as Configuration
from search_crawl_client.exceptions import OpenApiException as OpenApiException
from search_crawl_client.exceptions import ApiTypeError as ApiTypeError
from search_crawl_client.exceptions import ApiValueError as ApiValueError
from search_crawl_client.exceptions import ApiKeyError as ApiKeyError
from search_crawl_client.exceptions import ApiAttributeError as ApiAttributeError
from search_crawl_client.exceptions import ApiException as ApiException

# import models into sdk package
from search_crawl_client.models.cache_config import CacheConfig as CacheConfig
from search_crawl_client.models.crawl_config import CrawlConfig as CrawlConfig
from search_crawl_client.models.crawl_extract_request import CrawlExtractRequest as CrawlExtractRequest
from search_crawl_client.models.crawl_request import CrawlRequest as CrawlRequest
from search_crawl_client.models.crawl_request_with_url import CrawlRequestWithUrl as CrawlRequestWithUrl
from search_crawl_client.models.crawl_request_with_urls import CrawlRequestWithUrls as CrawlRequestWithUrls
from search_crawl_client.models.crawl_scope import CrawlScope as CrawlScope
from search_crawl_client.models.engine_preset_key import EnginePresetKey as EnginePresetKey
from search_crawl_client.models.engines import Engines as Engines
from search_crawl_client.models.extract_request import ExtractRequest as ExtractRequest
from search_crawl_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from search_crawl_client.models.output_format import OutputFormat as OutputFormat
from search_crawl_client.models.scrape_result import ScrapeResult as ScrapeResult
from search_crawl_client.models.search_crawl_extract_request import SearchCrawlExtractRequest as SearchCrawlExtractRequest
from search_crawl_client.models.search_crawl_request import SearchCrawlRequest as SearchCrawlRequest
from search_crawl_client.models.search_crawl_result import SearchCrawlResult as SearchCrawlResult
from search_crawl_client.models.search_request import SearchRequest as SearchRequest
from search_crawl_client.models.search_result import SearchResult as SearchResult
from search_crawl_client.models.validation_error import ValidationError as ValidationError
from search_crawl_client.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner
