# coding: utf-8

# flake8: noqa

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BaseCrawlRequest",
    "CacheConfig",
    "CrawlManyRequest",
    "CrawlRequest",
    "GeneralSearchCrawlRequest",
    "GeneralSearchCrawlResult",
    "GeneralSearchRequest",
    "GeneralSearchResult",
    "HTTPValidationError",
    "ImageSearchCrawlRequest",
    "ImageSearchCrawlResult",
    "ImageSearchRequest",
    "ImageSearchResult",
    "ScrapeResult",
    "ValidationError",
    "ValidationErrorLocInner",
]

# import apis into sdk package
from search_crawl_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from search_crawl_client.api_response import ApiResponse as ApiResponse
from search_crawl_client.api_client import ApiClient as ApiClient
from search_crawl_client.configuration import Configuration as Configuration
from search_crawl_client.exceptions import OpenApiException as OpenApiException
from search_crawl_client.exceptions import ApiTypeError as ApiTypeError
from search_crawl_client.exceptions import ApiValueError as ApiValueError
from search_crawl_client.exceptions import ApiKeyError as ApiKeyError
from search_crawl_client.exceptions import ApiAttributeError as ApiAttributeError
from search_crawl_client.exceptions import ApiException as ApiException

# import models into sdk package
from search_crawl_client.models.base_crawl_request import BaseCrawlRequest as BaseCrawlRequest
from search_crawl_client.models.cache_config import CacheConfig as CacheConfig
from search_crawl_client.models.crawl_many_request import CrawlManyRequest as CrawlManyRequest
from search_crawl_client.models.crawl_request import CrawlRequest as CrawlRequest
from search_crawl_client.models.general_search_crawl_request import GeneralSearchCrawlRequest as GeneralSearchCrawlRequest
from search_crawl_client.models.general_search_crawl_result import GeneralSearchCrawlResult as GeneralSearchCrawlResult
from search_crawl_client.models.general_search_request import GeneralSearchRequest as GeneralSearchRequest
from search_crawl_client.models.general_search_result import GeneralSearchResult as GeneralSearchResult
from search_crawl_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from search_crawl_client.models.image_search_crawl_request import ImageSearchCrawlRequest as ImageSearchCrawlRequest
from search_crawl_client.models.image_search_crawl_result import ImageSearchCrawlResult as ImageSearchCrawlResult
from search_crawl_client.models.image_search_request import ImageSearchRequest as ImageSearchRequest
from search_crawl_client.models.image_search_result import ImageSearchResult as ImageSearchResult
from search_crawl_client.models.scrape_result import ScrapeResult as ScrapeResult
from search_crawl_client.models.validation_error import ValidationError as ValidationError
from search_crawl_client.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner
